# Site settings
title: Sunah Suh
email: contact@sunahsuh.com
description: "Hi, I'm Sunah, a software engineer at Etsy working remotely in Chicago, IL."
baseurl: ""
url: "http://sunahsuh.com"

# Build settings
markdown: kramdown
permalink: pretty
